[project]
name = 'usabtc-smart-contracts'
description = 'A SIP-010 compliant token for USABTC.'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.usabtc]
path = 'contracts/usabtc.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
