[project]
name = 'usabtc-smart-contracts'
description = 'A SIP-010 compliant token for USABTC.'
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.sbtc-registry]
path = 'contracts/sbtc/sbtc-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.sbtc-token]
path = 'contracts/sbtc/sbtc-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.usabtc-token]
path = 'contracts/usabtc-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
